import {
  GET_CLINIC_DETAIL,
  // GET_FILTERED_BRANCH_CLIENT_RECORDS,
  GET_BRANCH_PENDING_INVITATIONS,
  GET_USER_PENDING_INVITATIONS,
  GET_BRANCH_DEVICE_ASSIGNMENTS,
  GET_BRANCH_DEVICE_ASSIGNMENT_REQUESTS,
  GET_BRANCH_PET_RECORDS,
} from "./clinic";
import { GET_IOT_EVENT_LOGS, GET_IOT_DEVICE_BY_ID } from "./device";

export const clinicQueries = {
  GetClinicDetail: GET_CLINIC_DETAIL,
  GetBranchPetRecords: GET_BRANCH_PET_RECORDS,
  GetBranchPendingInvitations: GET_BRANCH_PENDING_INVITATIONS,
  GetUserPendingInvitations: GET_USER_PENDING_INVITATIONS,
  GetBranchDeviceAssignments: GET_BRANCH_DEVICE_ASSIGNMENTS,
  GetBranchDeviceAssignmentRequests: GET_BRANCH_DEVICE_ASSIGNMENT_REQUESTS,
};

export const deviceQueries = {
  GetIotEventLogs: GET_IOT_EVENT_LOGS,
  GetIotDeviceById: GET_IOT_DEVICE_BY_ID,
};
