import {
  GET_CLINIC_DETAIL,
  GET_BRANCH_CLIENT_RECORDS,
  GET_BRANCH_PENDING_INVITATIONS,
  GET_USER_PENDING_INVITATIONS,
  GET_BRANCH_DEVICE_ASSIGNMENTS,
} from "./clinic";

export const clinicQueries = {
  GetClinicDetail: GET_CLINIC_DETAIL,
  GetBranchClientRecords: GET_BRANCH_CLIENT_RECORDS,
  GetBranchPendingInvitations: GET_BRANCH_PENDING_INVITATIONS,
  GetUserPendingInvitations: GET_USER_PENDING_INVITATIONS,
  GetBranchDeviceAssignments: GET_BRANCH_DEVICE_ASSIGNMENTS,
};
