type Country = {
  name: string;
  code: string;
  iso: string;
  flag: string;
  mask: string | string[];
  regex?: RegExp;
};

const countries: Country[] = [
  {
    name: "Afghanistan",
    code: "+93",
    iso: "AF",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/af.svg",
    mask: "##-###-####",
    regex: /^(\d{2}-\d{3}-\d{4})$/,
  },
  {
    name: "United States",
    code: "+1",
    iso: "US",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/us.svg",
    mask: "(###) ###-####",
    regex: /^\(\d{3}\) \d{3}-\d{4}$/,
  },
  {
    name: "Canada",
    code: "+1",
    iso: "CA",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ca.svg",
    mask: "(###) ###-####",
    regex: /^\(\d{3}\) \d{3}-\d{4}$/,
  },
  {
    name: "United Kingdom",
    code: "+44",
    iso: "GB",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/gb.svg",
    mask: "#### ######",
    regex: /^\d{4} \d{6}$/,
  },
  {
    name: "Germany",
    code: "+49",
    iso: "DE",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/de.svg",
    mask: "#### ########",
    regex: /^\d{4} \d{8}$/,
  },
  {
    name: "France",
    code: "+33",
    iso: "FR",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/fr.svg",
    mask: "# ## ## ## ##",
    regex: /^\d \d{2} \d{2} \d{2} \d{2}$/,
  },
  {
    name: "Italy",
    code: "+39",
    iso: "IT",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/it.svg",
    mask: "### #######",
    regex: /^\d{3} \d{7}$/,
  },
  {
    name: "Spain",
    code: "+34",
    iso: "ES",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/es.svg",
    mask: "### ### ###",
    regex: /^\d{3} \d{3} \d{3}$/,
  },
  {
    name: "Brazil",
    code: "+55",
    iso: "BR",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/br.svg",
    mask: "(##) ####-####",
    regex: /^\(\d{2}\) \d{4}-\d{4}$/,
  },
  {
    name: "China",
    code: "+86",
    iso: "CN",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/cn.svg",
    mask: "### #### ####",
    regex: /^\d{3} \d{4} \d{4}$/,
  },
  {
    name: "Japan",
    code: "+81",
    iso: "JP",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/jp.svg",
    mask: "## #### ####",
    regex: /^\d{2} \d{4} \d{4}$/,
  },
  {
    name: "India",
    code: "+91",
    iso: "IN",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/in.svg",
    mask: "#####-#####",
    regex: /^\d{5}-\d{5}$/,
  },
  {
    name: "Russia",
    code: "+7",
    iso: "RU",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ru.svg",
    mask: "### ###-##-##",
    regex: /^\d{3} \d{3}-\d{2}-\d{2}$/,
  },
  {
    name: "Australia",
    code: "+61",
    iso: "AU",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/au.svg",
    mask: "#### ### ###",
    regex: /^\d{4} \d{3} \d{3}$/,
  },
  {
    name: "South Korea",
    code: "+82",
    iso: "KR",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/kr.svg",
    mask: "##-####-####",
    regex: /^\d{2}-\d{4}-\d{4}$/,
  },
  {
    name: "Mexico",
    code: "+52",
    iso: "MX",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/mx.svg",
    mask: "## #### ####",
    regex: /^\d{2} \d{4} \d{4}$/,
  },
  {
    name: "Argentina",
    code: "+54",
    iso: "AR",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ar.svg",
    mask: "## ####-####",
    regex: /^\d{2} \d{4}-\d{4}$/,
  },
  {
    name: "South Africa",
    code: "+27",
    iso: "ZA",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/za.svg",
    mask: "### ### ####",
    regex: /^\d{3} \d{3} \d{4}$/,
  },
  {
    name: "Turkey",
    code: "+90",
    iso: "TR",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/tr.svg",
    mask: "(###) ### ####",
    regex: /^\(\d{3}\) \d{3} \d{4}$/,
  },
  {
    name: "Saudi Arabia",
    code: "+966",
    iso: "SA",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/sa.svg",
    mask: "### ### ####",
    regex: /^\d{3} \d{3} \d{4}$/,
  },
  {
    name: "United Arab Emirates",
    code: "+971",
    iso: "AE",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ae.svg",
    mask: "### ### ####",
    regex: /^\d{3} \d{3} \d{4}$/,
  },
  {
    name: "Iran",
    code: "+98",
    iso: "IR",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ir.svg",
    mask: "### ### ####",
    regex: /^\d{3} \d{3} \d{4}$/,
  },
  {
    name: "Indonesia",
    code: "+62",
    iso: "ID",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/id.svg",
    mask: "### #### ####",
    regex: /^\d{3} \d{4} \d{4}$/,
  },
  {
    name: "Malaysia",
    code: "+60",
    iso: "MY",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/my.svg",
    mask: "##-#### ####",
    regex: /^\d{2}-\d{4} \d{4}$/,
  },
  {
    name: "Thailand",
    code: "+66",
    iso: "TH",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/th.svg",
    mask: "##-####-####",
    regex: /^\d{2}-\d{4}-\d{4}$/,
  },
  {
    name: "Vietnam",
    code: "+84",
    iso: "VN",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/vn.svg",
    mask: "#### #### ####",
    regex: /^\d{4} \d{4} \d{4}$/,
  },
  {
    name: "Philippines",
    code: "+63",
    iso: "PH",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ph.svg",
    mask: "#### #######",
    regex: /^\d{4} \d{7}$/,
  },
  {
    name: "Pakistan",
    code: "+92",
    iso: "PK",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/pk.svg",
    mask: "###-#######",
    regex: /^\d{3}-\d{7}$/,
  },
  {
    name: "Bangladesh",
    code: "+880",
    iso: "BD",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/bd.svg",
    mask: "###-###-###",
    regex: /^\d{3}-\d{3}-\d{3}$/,
  },
  {
    name: "Egypt",
    code: "+20",
    iso: "EG",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/eg.svg",
    mask: "### ### ####",
    regex: /^\d{3} \d{3} \d{4}$/,
  },
  {
    name: "Nigeria",
    code: "+234",
    iso: "NG",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ng.svg",
    mask: "### ### ####",
    regex: /^\d{3} \d{3} \d{4}$/,
  },
  {
    name: "Kenya",
    code: "+254",
    iso: "KE",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ke.svg",
    mask: "### ### ####",
    regex: /^\d{3} \d{3} \d{4}$/,
  },
  {
    name: "Ghana",
    code: "+233",
    iso: "GH",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/gh.svg",
    mask: "### ### ####",
    regex: /^\d{3} \d{3} \d{4}$/,
  },
  {
    name: "Colombia",
    code: "+57",
    iso: "CO",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/co.svg",
    mask: "### ### ####",
    regex: /^\d{3} \d{3} \d{4}$/,
  },
  {
    name: "Chile",
    code: "+56",
    iso: "CL",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/cl.svg",
    mask: "## #### ####",
    regex: /^\d{2} \d{4} \d{4}$/,
  },
  {
    name: "Peru",
    code: "+51",
    iso: "PE",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/pe.svg",
    mask: "### ### ####",
    regex: /^\d{3} \d{3} \d{4}$/,
  },
  {
    name: "Venezuela",
    code: "+58",
    iso: "VE",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ve.svg",
    mask: "### ### ####",
    regex: /^\d{3} \d{3} \d{4}$/,
  },
  {
    name: "Israel",
    code: "+972",
    iso: "IL",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/il.svg",
    mask: "###-###-####",
    regex: /^\d{3}-\d{3}-\d{4}$/,
  },
  {
    name: "Jordan",
    code: "+962",
    iso: "JO",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/jo.svg",
    mask: "### #### ###",
    regex: /^\d{3} \d{4} \d{3}$/,
  },
  {
    name: "Lebanon",
    code: "+961",
    iso: "LB",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/lb.svg",
    mask: "## ### ###",
    regex: /^\d{2} \d{3} \d{3}$/,
  },
  {
    name: "Iraq",
    code: "+964",
    iso: "IQ",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/iq.svg",
    mask: "### ### ####",
    regex: /^\d{3} \d{3} \d{4}$/,
  },
  {
    name: "Syria",
    code: "+963",
    iso: "SY",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/sy.svg",
    mask: "### ### ####",
    regex: /^\d{3} \d{3} \d{4}$/,
  },
  {
    name: "Morocco",
    code: "+212",
    iso: "MA",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ma.svg",
    mask: "###-###-###",
    regex: /^\d{3}-\d{3}-\d{3}$/,
  },
  {
    name: "Algeria",
    code: "+213",
    iso: "DZ",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/dz.svg",
    mask: "### ### ####",
    regex: /^\d{3} \d{3} \d{4}$/,
  },
  {
    name: "Tunisia",
    code: "+216",
    iso: "TN",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/tn.svg",
    mask: "## ### ###",
    regex: /^\d{2} \d{3} \d{3}$/,
  },
  {
    name: "Libya",
    code: "+218",
    iso: "LY",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ly.svg",
    mask: "## ### ####",
    regex: /^\d{2} \d{3} \d{4}$/,
  },
  {
    name: "Sudan",
    code: "+249",
    iso: "SD",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/sd.svg",
    mask: "### ### ####",
    regex: /^\d{3} \d{3} \d{4}$/,
  },
];

export { countries };